### ISSUE TITLE
Set-up the server name 

### ISSUE THREAD

**Issue by theozanchi** [theozanchi/42_Berlin_webserv#81]

**Comment by sepber** [comment]
curl --resolve default.com:8080:127.0.0.1 -v http://default.com:8080/index.html

should work for our default config server.
Curl -- resolves takes a parameter of the format HOST:PORT:ADDRESS it forces to resolve the HOST to the ADDRESS when connection to the specified PORT but only for the duration of the curl command. This bypasses any need for DNS lookups or changes to the hosts file.

Right now we get BAD REQUEST because the checkInput() in the Response Class throws Wrong Host Exceptions when it doesn't find a server with request.getHostname() (default.com:8080). When catching that exception we need a second check to check if we can find a server with the port and the server name (default.com:8080) and only then if we cannot find throw the WrongHostexception!
